/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package genetic.algorithm;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest
{
    @Test void testCrossoverLength()
    {
        String s = App.crossover("ABCDEF", "abcdef");
        assertEquals(6, s.length());
    }
}
